# Site settings
title:          大漠留香的博客
description:    风吹流水，大漠留香

markdown:       kramdown
timezone:       Asia/Shanghai
permalink:      /:year/:month/:day/:title
paginate:       1
paginate_path:  "page:num"