# Site settings
# markdown:       redcarpet
markdown:       kramdown
kramdown:
  input:        GFM

title:          Zhenrui Chen' Blog
author:         Zhenrui Chen
description:    风吹流水，大漠留香
url:            http://zhenruichen.com

timezone:       Asia/Shanghai
paginate:       10
paginate_path:  "page:num"

homepage:
  name:         首页
  url:          /index.html
archives:
  name:         归档
  url:          /archives.html 
tags-all:
  name:         标签
  url:          /tags.html 
update:
  name:         记录
  url:          /update.html
about:
  name:         关于
  url:          /about.html
feed:
  name:         RSS 订阅
  url:          /feed.xml

excerpt_separator:  ""

# Gems
gems:           [jekyll-paginate]


