# Site settings
# markdown:       redcarpet
markdown:       kramdown
kramdown:
  input:        GFM

title:          Zhenrui Chen' Blog
description:    风吹流水，大漠留香
url:            http://zhenruichen.com/

timezone:       Asia/Shanghai
permalink:      /:year/:month/:day/:title
paginate:       10
paginate_path:  "page:num"

homepage:
  name:         首页
  url:          /index.html
update:
  name:         功能
  url:          /update.html
feed:
  name:         订阅
  url:          /feed.xml
about:
  name:         关于
  url:          /about.html
  
excerpt_separator:  ""


