# Site settings
title:          Zhenrui Chen' Blog
description:    风吹流水，大漠留香

timezone:       Asia/Shanghai
permalink:      /:year/:month/:day/:title
paginate:       10
paginate_path:  "page:num"

homepage:       首页
website:        网站建设
aboutme:        关于