# Site settings
markdown:       kramdown

title:          Zhenrui Chen' Blog
description:    风吹流水，大漠留香
url:            http://zhenruichen.com/

timezone:       Asia/Shanghai
permalink:      /:year/:month/:day/:title
paginate:       10
paginate_path:  "page:num"

homepage:       首页
update:         功能
feed:           订阅
about:          关于

excerpt_separator:  ""